import React, { useEffect, useState } from 'react';
import { useAuth } from '../AuthContext';
import { db, handleFirestoreError, OperationType } from '../firebase';
import { collection, query, where, onSnapshot, addDoc, Timestamp } from 'firebase/firestore';
import { motion } from 'motion/react';
import { TrendingUp, PieChart, Wallet, ArrowRight, Sparkles, CheckCircle2, Loader2 } from 'lucide-react';

const RecommendationCard: React.FC<{ rec: any; onInvest: (rec: any) => void }> = ({ rec, onInvest }) => (
  <motion.div
    whileHover={{ y: -5 }}
    className="p-8 bg-zinc-900 border border-zinc-800 rounded-3xl shadow-xl space-y-6 relative overflow-hidden group"
  >
    <div className="absolute top-0 right-0 p-6 opacity-10 group-hover:opacity-20 transition-opacity">
      <TrendingUp size={80} />
    </div>
    
    <div className="flex items-center justify-between">
      <div className="w-12 h-12 bg-emerald-500/10 rounded-2xl flex items-center justify-center text-emerald-500">
        <Sparkles size={24} />
      </div>
      <div className="text-right">
        <p className="text-xs text-zinc-500 font-bold uppercase tracking-wider">Predicted Return</p>
        <p className="text-2xl font-black text-emerald-500">+{rec.predictedReturn}%</p>
      </div>
    </div>

    <div className="space-y-2">
      <h3 className="text-2xl font-black tracking-tight">{rec.type}</h3>
      <p className="text-zinc-400 leading-relaxed">{rec.reason}</p>
    </div>

    <div className="pt-6 border-t border-zinc-800 flex items-center justify-between">
      <div className="flex items-center space-x-2 text-sm text-zinc-500">
        <CheckCircle2 size={16} className="text-emerald-500" />
        <span>AI Verified</span>
      </div>
      <button
        onClick={() => onInvest(rec)}
        className="flex items-center space-x-2 bg-emerald-600 text-white px-6 py-2 rounded-xl font-bold hover:bg-emerald-500 transition-all"
      >
        <span>Invest Now</span>
        <ArrowRight size={18} />
      </button>
    </div>
  </motion.div>
);

const Recommendations: React.FC = () => {
  const { user, profile } = useAuth();
  const [recommendations, setRecommendations] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!user) return;
    const q = query(collection(db, 'recommendations'), where('uid', '==', user.uid));
    const unsubscribe = onSnapshot(q, (snap) => {
      const data = snap.docs
        .map(doc => ({ id: doc.id, ...doc.data() } as any))
        .sort((a, b) => (b.date?.toDate?.() || 0) - (a.date?.toDate?.() || 0));
      setRecommendations(data);
    });
    return () => unsubscribe();
  }, [user]);

  const handleInvest = async (rec: any) => {
    if (!user) return;
    setLoading(true);
    try {
      // Create a dummy investment based on recommendation
      await addDoc(collection(db, 'investments'), {
        uid: user.uid,
        type: rec.type,
        amount: 5000, // Default amount for demo
        tenure: 5,
        expectedReturn: rec.predictedReturn,
        date: Timestamp.now(),
      });
      alert(`Investment in ${rec.type} successful!`);
    } catch (error) {
      handleFirestoreError(error, OperationType.WRITE, 'investments');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <h2 className="text-3xl font-black tracking-tight">AI Recommendations</h2>
          <p className="text-zinc-500">Personalized investment strategies generated by our ML models for your profile.</p>
        </div>
        <div className="w-12 h-12 bg-emerald-500/10 rounded-2xl flex items-center justify-center text-emerald-500">
          <Sparkles size={24} />
        </div>
      </div>

      {!profile?.riskTolerance && (
        <div className="p-12 bg-zinc-900 border border-zinc-800 rounded-3xl text-center space-y-6">
          <div className="w-16 h-16 bg-zinc-800 rounded-2xl flex items-center justify-center mx-auto text-zinc-500">
            <PieChart size={32} />
          </div>
          <div className="space-y-2">
            <h3 className="text-xl font-bold">No Profile Data Found</h3>
            <p className="text-zinc-500 max-w-md mx-auto">Complete your financial profile to unlock personalized AI investment recommendations.</p>
          </div>
          <a href="/profile" className="inline-block bg-emerald-600 text-white px-8 py-3 rounded-2xl font-bold">Setup Profile</a>
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {recommendations.map((rec) => (
          <RecommendationCard key={rec.id} rec={rec} onInvest={handleInvest} />
        ))}
      </div>

      {recommendations.length > 0 && (
        <div className="bg-zinc-900/50 border border-zinc-800 p-8 rounded-3xl space-y-4">
          <h3 className="text-xl font-bold">Why these recommendations?</h3>
          <p className="text-zinc-400 leading-relaxed">
            Our hybrid system combines rule-based financial logic with a Linear Regression model. 
            The rule-based system selects the asset class (Stocks, Mutual Funds, or Fixed Deposits) 
            based on your risk tolerance, while the ML model predicts the expected return based on 
            your income, age, and savings patterns.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-4">
            <div className="p-4 bg-zinc-800 rounded-2xl space-y-1">
              <p className="text-xs text-zinc-500 font-bold uppercase">Low Risk</p>
              <p className="font-bold">Fixed Deposits</p>
            </div>
            <div className="p-4 bg-zinc-800 rounded-2xl space-y-1">
              <p className="text-xs text-zinc-500 font-bold uppercase">Medium Risk</p>
              <p className="font-bold">Mutual Funds</p>
            </div>
            <div className="p-4 bg-zinc-800 rounded-2xl space-y-1">
              <p className="text-xs text-zinc-500 font-bold uppercase">High Risk</p>
              <p className="font-bold">Stocks</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Recommendations;
